version: 'Xemime CLI Build #{Build}'

os: Visual Studio 2017

platform:
  - Win32
  - x64

configuration:
  - Release

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - cmd: java --version
